language: go
go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - go get -u -v github.com/spf13/pflag github.com/spf13/viper github.com/ahmetb/govvv github.com/golang/lint/golint

script:
  - govvv build